# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  sync:
    cmds:
      - scp -r opt-bin/* 88u:/opt/bin
      - scp -r opt-usr-bin/* 88u:/opt/usr/bin
      - scp -r opt-etc/* 88u:/opt/etc
      - scp -r opt-etc-init.d/* 88u:/opt/etc/init.d
      - ssh 88u "/opt/usr/bin/env_check.sh"

  test:
    cmds:
      - v2ray test --config opt-etc/v2ray.json

  dev:
    cmds:
      - v2ray run --config opt-etc/v2ray.json

  restart:
    cmds:
      - ssh 88u "/opt/etc/patch_router"