#!/bin/sh

ENABLED=yes
PROCS=a88u
DIR="/opt/bin"
ARGS="agent"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

. /opt/etc/init.d/rc.func